### ISSUE TITLE
Reuse Keycloak redirectUris is pointing to localhost

### ISSUE THREAD

**Issue by wengkee** [microcks/microcks.github.io#7]
### Describe the bug

In [Reusing Existing Keycloak](https://microcks.io/documentation/installing/deployment-options/#reusing-existing-keycloak) section, there are 2 realm JSON files being listed as an example. In both JSON files, the redirectUris is pointing to localhost:8080, in the case where we are deploying this to non-local environment, this will not work.

We should add a suggestion to update the realm file accordingly. I can make a pull request, but can you let me know how I can render and test the website locally? I can't find the guide and double-clicking on the index.html doesn't seem to render properly.

### Attach any resources that can help us understand the issue.

https://github.com/microcks/microcks/blob/master/install/keycloak-microcks-realm-addons.json#L80

https://github.com/microcks/microcks/blob/master/install/keycloak-microcks-realm-full.json#L128

**Comment by wengkee** [comment]
![image](https://user-images.githubusercontent.com/47697491/232071375-9d31f328-6632-4a62-8fa4-44ef6b1eb26d.png)

**Comment by nmasse-itix** [comment]
I believe the website is built with hugo.

```sh
git clone https://github.com/microcks/microcks.io
cd microcks.io
hugo serve
```

The pages on this repo are the generated html files served by GitHub Pages. 

@lbroudoux to confirm?

**Comment by lbroudoux** [comment]
Yes exactly. Thanks @wengkee for the suggestions, you're absolutely right: it would be better to add directives to update the realm files before importing them. Would you mind sending a PR to https://github.com/microcks/microcks.io?
I love to push where credit is due 😉

**Comment by wengkee** [comment]
closing this issue as it is reported in the wrong repo
